<div class="confidence">
    <div class="confidence-header">
        <div>
            <h3>Confidence Level Interpretation</h3>
            <p>
                A guide for interpreting the confidence metric generated by the prototype system.
            </p>
        </div>
    </div>

    <div class="confidence-guide">

        <div class="confidence-item confidence-item-low">
            <div class="confidence-dot confidence-low"></div>

            <div class="confidence-content">
                <strong>Orange</strong>
                <span>0–49%</span>
                <p>Low Confidence</p>
            </div>
        </div>

        <div class="confidence-item confidence-item-moderate">
            <div class="confidence-dot confidence-moderate"></div>

            <div class="confidence-content">
                <strong>Green</strong>
                <span>50–79%</span>
                <p>Moderate Confidence</p>
            </div>
        </div>
        
        <div class="confidence-item confidence-item-high">
            <div class="confidence-dot confidence-high"></div>

            <div class="confidence-content">
                <strong>Blue</strong>
                <span>80–100%</span>
                <p>High Confidence</p>
            </div>
        </div>

    </div>

    <p class="confidence-note">
        Confidence levels are based on a proposed prototype evaluation metric
        that combines motif similarity to the MotifVoter consensus,
        sequence coverage, relative internal score,
        and runtime efficiency.
    </p>
</div>